// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1228057230;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_loom_app',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiSimpleAppDatabaseCreatePost({
    required AppDatabase that,
    required Post post,
  });

  Future<void> crateApiSimpleAppDatabaseCreateTotem({
    required AppDatabase that,
    required Totem totem,
  });

  Future<void> crateApiSimpleAppDatabaseCreateUser({
    required AppDatabase that,
    required User user,
  });

  Future<List<Post>> crateApiSimpleAppDatabaseGetAllPosts({
    required AppDatabase that,
  });

  Future<List<Totem>> crateApiSimpleAppDatabaseGetAllTotems({
    required AppDatabase that,
  });

  Future<List<User>> crateApiSimpleAppDatabaseGetAllUsers({
    required AppDatabase that,
  });

  Future<Post> crateApiSimpleAppDatabaseGetPostById({
    required AppDatabase that,
    required String uuid,
  });

  Future<List<String>> crateApiSimpleAppDatabaseGetPostIdsInRange({
    required AppDatabase that,
    required DateTime start,
    required DateTime end,
  });

  Future<User> crateApiSimpleAppDatabaseGetUserById({
    required AppDatabase that,
    required String uuid,
  });

  AppDatabase crateApiSimpleAppDatabaseNew({required String path});

  Future<void> crateApiSimpleAppDatabaseUpdateTotemLastContact({
    required AppDatabase that,
    required String uuid,
    required DateTime lastContact,
  });

  Future<void> crateApiSimpleAppDatabaseUpdateUser({
    required AppDatabase that,
    required User user,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AppDatabase;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AppDatabase;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_AppDatabasePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiSimpleAppDatabaseCreatePost({
    required AppDatabase that,
    required Post post,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppDatabase(
            that,
            serializer,
          );
          sse_encode_box_autoadd_post(post, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleAppDatabaseCreatePostConstMeta,
        argValues: [that, post],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleAppDatabaseCreatePostConstMeta =>
      const TaskConstMeta(
        debugName: "AppDatabase_create_post",
        argNames: ["that", "post"],
      );

  @override
  Future<void> crateApiSimpleAppDatabaseCreateTotem({
    required AppDatabase that,
    required Totem totem,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppDatabase(
            that,
            serializer,
          );
          sse_encode_box_autoadd_totem(totem, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleAppDatabaseCreateTotemConstMeta,
        argValues: [that, totem],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleAppDatabaseCreateTotemConstMeta =>
      const TaskConstMeta(
        debugName: "AppDatabase_create_totem",
        argNames: ["that", "totem"],
      );

  @override
  Future<void> crateApiSimpleAppDatabaseCreateUser({
    required AppDatabase that,
    required User user,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppDatabase(
            that,
            serializer,
          );
          sse_encode_box_autoadd_user(user, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleAppDatabaseCreateUserConstMeta,
        argValues: [that, user],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleAppDatabaseCreateUserConstMeta =>
      const TaskConstMeta(
        debugName: "AppDatabase_create_user",
        argNames: ["that", "user"],
      );

  @override
  Future<List<Post>> crateApiSimpleAppDatabaseGetAllPosts({
    required AppDatabase that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppDatabase(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_post,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleAppDatabaseGetAllPostsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleAppDatabaseGetAllPostsConstMeta =>
      const TaskConstMeta(
        debugName: "AppDatabase_get_all_posts",
        argNames: ["that"],
      );

  @override
  Future<List<Totem>> crateApiSimpleAppDatabaseGetAllTotems({
    required AppDatabase that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppDatabase(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_totem,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleAppDatabaseGetAllTotemsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleAppDatabaseGetAllTotemsConstMeta =>
      const TaskConstMeta(
        debugName: "AppDatabase_get_all_totems",
        argNames: ["that"],
      );

  @override
  Future<List<User>> crateApiSimpleAppDatabaseGetAllUsers({
    required AppDatabase that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppDatabase(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_user,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleAppDatabaseGetAllUsersConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleAppDatabaseGetAllUsersConstMeta =>
      const TaskConstMeta(
        debugName: "AppDatabase_get_all_users",
        argNames: ["that"],
      );

  @override
  Future<Post> crateApiSimpleAppDatabaseGetPostById({
    required AppDatabase that,
    required String uuid,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppDatabase(
            that,
            serializer,
          );
          sse_encode_String(uuid, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_post,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleAppDatabaseGetPostByIdConstMeta,
        argValues: [that, uuid],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleAppDatabaseGetPostByIdConstMeta =>
      const TaskConstMeta(
        debugName: "AppDatabase_get_post_by_id",
        argNames: ["that", "uuid"],
      );

  @override
  Future<List<String>> crateApiSimpleAppDatabaseGetPostIdsInRange({
    required AppDatabase that,
    required DateTime start,
    required DateTime end,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppDatabase(
            that,
            serializer,
          );
          sse_encode_Chrono_Utc(start, serializer);
          sse_encode_Chrono_Utc(end, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleAppDatabaseGetPostIdsInRangeConstMeta,
        argValues: [that, start, end],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleAppDatabaseGetPostIdsInRangeConstMeta =>
      const TaskConstMeta(
        debugName: "AppDatabase_get_post_ids_in_range",
        argNames: ["that", "start", "end"],
      );

  @override
  Future<User> crateApiSimpleAppDatabaseGetUserById({
    required AppDatabase that,
    required String uuid,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppDatabase(
            that,
            serializer,
          );
          sse_encode_String(uuid, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_user,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleAppDatabaseGetUserByIdConstMeta,
        argValues: [that, uuid],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleAppDatabaseGetUserByIdConstMeta =>
      const TaskConstMeta(
        debugName: "AppDatabase_get_user_by_id",
        argNames: ["that", "uuid"],
      );

  @override
  AppDatabase crateApiSimpleAppDatabaseNew({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppDatabase,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleAppDatabaseNewConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleAppDatabaseNewConstMeta =>
      const TaskConstMeta(debugName: "AppDatabase_new", argNames: ["path"]);

  @override
  Future<void> crateApiSimpleAppDatabaseUpdateTotemLastContact({
    required AppDatabase that,
    required String uuid,
    required DateTime lastContact,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppDatabase(
            that,
            serializer,
          );
          sse_encode_String(uuid, serializer);
          sse_encode_Chrono_Utc(lastContact, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleAppDatabaseUpdateTotemLastContactConstMeta,
        argValues: [that, uuid, lastContact],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleAppDatabaseUpdateTotemLastContactConstMeta =>
      const TaskConstMeta(
        debugName: "AppDatabase_update_totem_last_contact",
        argNames: ["that", "uuid", "lastContact"],
      );

  @override
  Future<void> crateApiSimpleAppDatabaseUpdateUser({
    required AppDatabase that,
    required User user,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppDatabase(
            that,
            serializer,
          );
          sse_encode_box_autoadd_user(user, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleAppDatabaseUpdateUserConstMeta,
        argValues: [that, user],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleAppDatabaseUpdateUserConstMeta =>
      const TaskConstMeta(
        debugName: "AppDatabase_update_user",
        argNames: ["that", "user"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AppDatabase => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppDatabase;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AppDatabase => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppDatabase;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  AppDatabase
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppDatabase(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AppDatabaseImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AppDatabase
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppDatabase(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AppDatabaseImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  DateTime dco_decode_Chrono_Utc(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeTimestamp(ts: dco_decode_i_64(raw).toInt(), isUtc: true);
  }

  @protected
  AppDatabase
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppDatabase(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AppDatabaseImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  Post dco_decode_box_autoadd_post(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_post(raw);
  }

  @protected
  Totem dco_decode_box_autoadd_totem(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_totem(raw);
  }

  @protected
  User dco_decode_box_autoadd_user(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_user(raw);
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Post> dco_decode_list_post(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_post).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<Totem> dco_decode_list_totem(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_totem).toList();
  }

  @protected
  List<User> dco_decode_list_user(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_user).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  Post dco_decode_post(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return Post(
      uuid: dco_decode_String(arr[0]),
      userId: dco_decode_String(arr[1]),
      title: dco_decode_String(arr[2]),
      body: dco_decode_String(arr[3]),
      timestamp: dco_decode_Chrono_Utc(arr[4]),
      image: dco_decode_opt_String(arr[5]),
      sourceTotem: dco_decode_String(arr[6]),
    );
  }

  @protected
  Totem dco_decode_totem(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Totem(
      uuid: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      location: dco_decode_String(arr[2]),
      lastContact: dco_decode_Chrono_Utc(arr[3]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  User dco_decode_user(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return User(
      uuid: dco_decode_String(arr[0]),
      username: dco_decode_String(arr[1]),
      status: dco_decode_String(arr[2]),
      bio: dco_decode_String(arr[3]),
      profilePicture: dco_decode_opt_String(arr[4]),
      lastContact: dco_decode_Chrono_Utc(arr[5]),
    );
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  AppDatabase
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppDatabase(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AppDatabaseImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AppDatabase
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppDatabase(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AppDatabaseImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_64(deserializer);
    return DateTime.fromMicrosecondsSinceEpoch(inner.toInt(), isUtc: true);
  }

  @protected
  AppDatabase
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppDatabase(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AppDatabaseImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  Post sse_decode_box_autoadd_post(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_post(deserializer));
  }

  @protected
  Totem sse_decode_box_autoadd_totem(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_totem(deserializer));
  }

  @protected
  User sse_decode_box_autoadd_user(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_user(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Post> sse_decode_list_post(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Post>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_post(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<Totem> sse_decode_list_totem(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Totem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_totem(deserializer));
    }
    return ans_;
  }

  @protected
  List<User> sse_decode_list_user(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <User>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_user(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Post sse_decode_post(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_uuid = sse_decode_String(deserializer);
    var var_userId = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_body = sse_decode_String(deserializer);
    var var_timestamp = sse_decode_Chrono_Utc(deserializer);
    var var_image = sse_decode_opt_String(deserializer);
    var var_sourceTotem = sse_decode_String(deserializer);
    return Post(
      uuid: var_uuid,
      userId: var_userId,
      title: var_title,
      body: var_body,
      timestamp: var_timestamp,
      image: var_image,
      sourceTotem: var_sourceTotem,
    );
  }

  @protected
  Totem sse_decode_totem(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_uuid = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_location = sse_decode_String(deserializer);
    var var_lastContact = sse_decode_Chrono_Utc(deserializer);
    return Totem(
      uuid: var_uuid,
      name: var_name,
      location: var_location,
      lastContact: var_lastContact,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  User sse_decode_user(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_uuid = sse_decode_String(deserializer);
    var var_username = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_bio = sse_decode_String(deserializer);
    var var_profilePicture = sse_decode_opt_String(deserializer);
    var var_lastContact = sse_decode_Chrono_Utc(deserializer);
    return User(
      uuid: var_uuid,
      username: var_username,
      status: var_status,
      bio: var_bio,
      profilePicture: var_profilePicture,
      lastContact: var_lastContact,
    );
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppDatabase(
    AppDatabase self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AppDatabaseImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppDatabase(
    AppDatabase self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AppDatabaseImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(
      PlatformInt64Util.from(self.microsecondsSinceEpoch),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppDatabase(
    AppDatabase self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AppDatabaseImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_post(Post self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_post(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_totem(Totem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_totem(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_user(User self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_user(self, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_post(List<Post> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_post(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_totem(List<Totem> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_totem(item, serializer);
    }
  }

  @protected
  void sse_encode_list_user(List<User> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_user(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_post(Post self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.uuid, serializer);
    sse_encode_String(self.userId, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.body, serializer);
    sse_encode_Chrono_Utc(self.timestamp, serializer);
    sse_encode_opt_String(self.image, serializer);
    sse_encode_String(self.sourceTotem, serializer);
  }

  @protected
  void sse_encode_totem(Totem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.uuid, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.location, serializer);
    sse_encode_Chrono_Utc(self.lastContact, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_user(User self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.uuid, serializer);
    sse_encode_String(self.username, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_String(self.bio, serializer);
    sse_encode_opt_String(self.profilePicture, serializer);
    sse_encode_Chrono_Utc(self.lastContact, serializer);
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class AppDatabaseImpl extends RustOpaque implements AppDatabase {
  // Not to be used by end users
  AppDatabaseImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  AppDatabaseImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_AppDatabase,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_AppDatabase,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_AppDatabasePtr,
  );

  Future<void> createPost({required Post post}) => RustLib.instance.api
      .crateApiSimpleAppDatabaseCreatePost(that: this, post: post);

  Future<void> createTotem({required Totem totem}) => RustLib.instance.api
      .crateApiSimpleAppDatabaseCreateTotem(that: this, totem: totem);

  Future<void> createUser({required User user}) => RustLib.instance.api
      .crateApiSimpleAppDatabaseCreateUser(that: this, user: user);

  Future<List<Post>> getAllPosts() =>
      RustLib.instance.api.crateApiSimpleAppDatabaseGetAllPosts(that: this);

  Future<List<Totem>> getAllTotems() =>
      RustLib.instance.api.crateApiSimpleAppDatabaseGetAllTotems(that: this);

  Future<List<User>> getAllUsers() =>
      RustLib.instance.api.crateApiSimpleAppDatabaseGetAllUsers(that: this);

  Future<Post> getPostById({required String uuid}) => RustLib.instance.api
      .crateApiSimpleAppDatabaseGetPostById(that: this, uuid: uuid);

  Future<List<String>> getPostIdsInRange({
    required DateTime start,
    required DateTime end,
  }) => RustLib.instance.api.crateApiSimpleAppDatabaseGetPostIdsInRange(
    that: this,
    start: start,
    end: end,
  );

  Future<User> getUserById({required String uuid}) => RustLib.instance.api
      .crateApiSimpleAppDatabaseGetUserById(that: this, uuid: uuid);

  Future<void> updateTotemLastContact({
    required String uuid,
    required DateTime lastContact,
  }) => RustLib.instance.api.crateApiSimpleAppDatabaseUpdateTotemLastContact(
    that: this,
    uuid: uuid,
    lastContact: lastContact,
  );

  Future<void> updateUser({required User user}) => RustLib.instance.api
      .crateApiSimpleAppDatabaseUpdateUser(that: this, user: user);
}
